### ISSUE TITLE
Should I make new file and copy for customize CommentsController?

### ISSUE THREAD

**Issue by popungco** [mgolovnia/mongoid_commentable#2]
First, my english is not good. Sorry about that.

I want customize CommentsController.

I cant find good way for this work.
So I just made new comments_controller.rb file and copy paste whole of code in my application.
It works ;) but I guess this way not good.
have some another way? 

ps. Maybe it cause from my poor rails knowledge...

**Comment by mgolovnia** [comment]
Hi! You can inherit your controller from the default one. Like this:

```
class NewCommentsController < CommentsController

def index
  do_whatever_you_want
end

def show
  do_whatever_you_want
  super
end


end
```

also, you need to map comments resources to a new controller in you routes.rb:
`resources :comments, :controller => "new_comments", :as => :comments`

**Comment by popungco** [comment]
It resolved. :)
Thank you.
