### ISSUE TITLE
How do I delete the comments database?

### ISSUE THREAD

**Issue by ghost** [mgolovnia/mongoid_commentable#3]
I have looked all over the mongo db for the comments and I cannot find them. Can you help me out.

**Comment by ghost** [comment]
db.collection.update({ }, { $set : { comments : [] } } );

This is what I am trying but it is not working. I understand now that they are a array within the commentable item.

**Comment by ghost** [comment]
db.collection.update({ }, { $set : { comments : [] } }, true ); close but still doesnt work. imagine someone else will want to know when I figure it out.

**Comment by ghost** [comment]
db.videos.update({ }, { $set : { comments : [] } }, false, multi= true } did the trick

**Comment by popungco** [comment]
In Model Class.

class Article
  include Mongoid::Document
  include Mongoid::Commentable

  field author
  field content

def mark_deleted(comment_id)

```
self.comments.find(comment_id).remove
```

end

end

Cause <code>Mongoid::Commentable</code> module missed set mark_deleted() function.

And then append scope In Comment class.

class Comment
...
  scope :non_deleted, where(deleted_at: nil)
  scope :order_by_path_asc, order_by([:path.to_sym, :asc])
...

end

In Controller

@comments = @article.comments.non_deleted.order_by_path_asc

It's not delete. Just hidden comment.

PS My english is not good ;(
